### PR TITLE
Make recipe noarch python

### PR DESCRIPTION
**Pull request by PrimozGodec**
Let's try to make this one noarch Python as discussed in https://github.com/conda-forge/httpx-feedstock/pull/58

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
@thewchan it seems it works. Can you check if I did everything right and merge?

**Comment by thewchan** [comment]
@PrimozGodec Thanks!

**Pull request merged**
