### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by PrimozGodec**
@florimondmanca and @tomchristie I created this repository to make HTTPX available on Conda. Since I do not want to be the only maintainer for Conda recipes and HTTPX is your library I invite you as maintainers for this recipe. 
Please comment with your agreements.

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by florimondmanca** [comment]
Hello!

Thanks for helping get HTTPX available to as many users as possible. :)

I'm not super familiar with Conda and I don't use it myself - what does being listed as a "maintainer" of this repo involve?

**Comment by PrimozGodec** [comment]
Hi,

we use HTTPX as a dependency in Orange3 library. Since Orange is also available on Conda all its requirements must be on Conda too. This is the main reason why I created the recipe. I am sure also some other users need the Conda version of HTTPX. 

Maintainers of the recipes mostly just merge pull requests opened by the conda-forge bot when the new version of the package appears on PyPI. If any requirement of the package change it must be added in the recipe. It doesn't take much time. 

I will still be involved in this recipe and primarily I can take care of it. I just wanted to add someone else in case I am away for a few weeks that someone else can merge the PRs.

**Comment by florimondmanca** [comment]
Sounds good to me!

**Comment by PrimozGodec** [comment]
@tomchristie what about you? Are you OK with being a maintainer?

**Comment by lovelydinosaur** [comment]
@PrimozGodec I'd prefer not, thanks. Already over-resourced as it is. 😃

**Comment by PrimozGodec** [comment]
Ok the I am adding only @florimondmanca

**Pull request merged**
