### PR TITLE
Fix dependencies according to package's dependencies

### PR DESCRIPTION
**Pull request by PrimozGodec**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I am modifying the dependencies according to [the dependencies in the httpx package](https://github.com/encode/httpx/blob/master/pyproject.toml).

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
@thewchan I fixed dependencies since they changed in the HTTPX package. Can you inspect that I did everything correctly?

**Comment by thewchan** [comment]
@conda-forge-admin please restart ci

**Comment by thewchan** [comment]
@PrimozGodec Thanks!

**Pull request merged**
